name: example_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - conda-forge::rasterio=1.3.7
  - conda-forge::pystac-client=0.7.5
  - conda-forge::matplotlib=3.8.0
  - jupyterlab=4
